name: CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]

defaults:
  run:
    shell: bash

env:
  PYTHONUTF8: "1"

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout the repository
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-python-and-git
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: uv sync -p ${{ matrix.python-version }} --group test
      - name: Test
        run: uv run pytest

  # Upload to Test PyPI.
  release-test-pypi:
    name: Publish in-dev package to test.pypi.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-python-and-git
        with:
          python-version: "3.12"

      - name: Install requirements
        shell: bash
        run: |
          uv pip install build bump-my-version

      - name: Set dev version
        shell: bash
        run: |
          export PR_NUMBER=$(gh pr view --json number -q .number || echo "")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "::notice::PR_NUMBER is: ${PR_NUMBER}"
          uv run bump-my-version bump dev --no-commit --no-tag -v

      - name: Package
        shell: bash
        run: |
          uv run python -m build

      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
